### ISSUE TITLE
Find terms failed if user have more than one payer in particular city

### ISSUE THREAD

**Issue by gelmiro** [dyrkin/luxmed-bot#12]
Hi,
I have case when in one city I have two payers in luxmed. Because of that when I try to find visit I got exception. Probably code expect that payer is automatically determine, but this doesn't work if you have more payer than one. In this case user must pick explicitly payer.
 `
2019-03-04 09:11:22 c.l.s.conversation.Book - Step execution failed
java.lang.RuntimeException: Can't determine payer id by user: 2, city: 5, clinic: None, service: 4502
        at scala.sys.package$.error(package.scala:27)
        at com.lbs.server.service.ApiService.$anonfun$getAvailableTerms$1(ApiService.scala:69)
        at scala.util.Either.flatMap(Either.scala:338)
        at com.lbs.server.service.ApiService.getAvailableTerms(ApiService.scala:57)
        at com.lbs.server.conversation.Book.$anonfun$requestTerm$1(Book.scala:135)
        at com.lbs.server.conversation.Book.$anonfun$requestTerm$1$adapted(Book.scala:134)
        at com.lbs.server.conversation.base.Conversation.executeCurrentStep(Conversation.scala:28)
        at com.lbs.server.conversation.base.Conversation.executeCurrentStep$(Conversation.scala:25)
        at com.lbs.server.conversation.Book.executeCurrentStep(Book.scala:22)
        at com.lbs.server.conversation.base.Interactional$$anon$1$$anonfun$receive$1.applyOrElse(Interactional.scala:33)
        at akka.actor.Actor.aroundReceive(Actor.scala:502)
        at akka.actor.Actor.aroundReceive$(Actor.scala:500)
        at com.lbs.server.conversation.base.Interactional$$anon$1.aroundReceive(Interactional.scala:28)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
`

Please add new option for selecting payer (maybe only if you have more than one)

**Comment by dyrkin** [comment]
Please check the latest version. If it works, please close the issue.
Also please note that already created monitorings will not work. You have to recreate them.

**Comment by dyrkin** [comment]
There will be one more step in the booking dialog in case the application fails to detect default payer.

**Comment by gelmiro** [comment]
Seems to work fine. Thx for fast action implementation.
