### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by vonProteus** [dyrkin/luxmed-bot#17]
hi i'm using your bot on my RPi via docker stack
```
version: '3.4'
services:
  luxmedbookingservice:
    image: eugenezadyra/luxmed-bot:latest-arm
    environment:
      - SECURITY_SECRET=${SECURITY_SECRET}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_HOST=database
    volumes:
    - lbs:/lbs

  database:
    image: postgres:10.6
    volumes:
    - postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=lbs
    - POSTGRES_PASSWORD=lsb123
    - POSTGRES_DB=lbs
    - TZ=Europe/Warsaw

volumes:
  postgres:
  lbs:
  
### Environment variables
# SECURITY_SECRET
# TELEGRAM_TOKEN
```

latest-arm is 170a26fed2b68bd96ce403c752aa3f0a6574e2555122234eecb64aac506ead90 in my case

and some times like every 5-15 minutes in last 16h it crash
this is log from last one

```
********************************************************,
Waiting for the database server to start on port 5432,
********************************************************,
******** Database Server has started ,
********************************************************,
Starting Luxmed Booking Service  ,
********************************************************,
,--.    ,-----.    ,---.   ,
|  |    |  |) /_  '   .-'  ,
|  |    |  .-.  \ `.  `-.  ,
|  '--. |  '--' / .-'    | ,
`-----' `------'  `-----'  ,
                           ,
2020-05-09 08:07:32 scala.App - Starting App on 24ba860c6a8f with PID 7 (/app/server.jar started by root in /app),
2020-05-09 08:07:32 scala.App - No active profile set, falling back to default profiles: default,
2020-05-09 08:08:15 o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data repositories in DEFAULT mode.,
2020-05-09 08:08:18 o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 2872ms. Found 0 repository interfaces.,
2020-05-09 08:08:45 c.z.h.HikariDataSource - HikariPool-1 - Starting...,
2020-05-09 08:08:50 c.z.h.HikariDataSource - HikariPool-1 - Start completed.,
2020-05-09 08:09:28 l.e.jvm.JdbcExecutor - SELECT COUNT(*) FROM public.databasechangeloglock,
2020-05-09 08:09:28 l.e.jvm.JdbcExecutor - SELECT COUNT(*) FROM public.databasechangeloglock,
2020-05-09 08:09:28 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:09:28 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:09:38 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:09:38 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:09:48 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:09:48 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:09:58 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:09:58 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:10:08 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:10:08 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:10:18 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:10:18 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:10:28 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:10:28 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:10:38 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:10:38 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:10:48 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:10:48 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:10:58 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:10:58 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:11:08 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:11:08 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:11:18 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:11:18 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:11:28 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:11:28 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:11:38 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:11:38 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:11:48 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:11:48 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:11:58 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:11:58 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:12:08 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:12:08 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:12:18 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:12:18 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:12:28 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:12:28 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:12:38 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:12:38 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:12:48 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:12:48 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:12:58 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:12:58 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:13:08 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:13:08 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:13:18 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:13:18 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:13:28 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:13:28 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:13:39 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:13:39 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:13:49 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:13:49 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:13:59 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:13:59 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:14:09 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:14:09 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:14:19 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:14:19 l.l.StandardLockService - Waiting for changelog lock....,
2020-05-09 08:14:29 l.e.jvm.JdbcExecutor - SELECT ID,LOCKED,LOCKGRANTED,LOCKEDBY FROM public.databasechangeloglock WHERE ID=1,
2020-05-09 08:14:29 o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by 172.18.0.3 (172.18.0.3) since 5/6/20 5:08 PM,
2020-05-09 08:14:29 c.z.h.HikariDataSource - HikariPool-1 - Shutdown initiated...,
2020-05-09 08:14:29 c.z.h.HikariDataSource - HikariPool-1 - Shutdown completed.,
2020-05-09 08:14:29 o.s.b.a.l.ConditionEvaluationReportLoggingListener - ,
,
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.,
2020-05-09 08:14:30 o.s.b.SpringApplication - Application run failed,
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by 172.18.0.3 (172.18.0.3) since 5/6/20 5:08 PM,
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1745),
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576),
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498),
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320),
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222),
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318),
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199),
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:307),
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199),
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1083),
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:853),
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546),
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775),
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397),
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316),
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260),
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248),
	at com.lbs.server.Boot$.delayedEndpoint$com$lbs$server$Boot$1(Boot.scala:12),
	at com.lbs.server.Boot$delayedInit$body.apply(Boot.scala:11),
	at scala.Function0.apply$mcV$sp(Function0.scala:39),
	at scala.Function0.apply$mcV$sp$(Function0.scala:39),
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17),
	at scala.App.$anonfun$main$1$adapted(App.scala:80),
	at scala.collection.immutable.List.foreach(List.scala:392),
	at scala.App.main(App.scala:80),
	at scala.App.main$(App.scala:78),
	at com.lbs.server.Boot$.main(Boot.scala:11),
	at com.lbs.server.Boot.main(Boot.scala),
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.lang.reflect.Method.invoke(Method.java:498),
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50),
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51),
Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by 172.18.0.3 (172.18.0.3) since 5/6/20 5:08 PM,
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:230),
	at liquibase.Liquibase.update(Liquibase.java:184),
	at liquibase.Liquibase.update(Liquibase.java:179),
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353),
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305),
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804),
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741),
	... 35 common frames omitted,
```

can you help?

**Comment by dyrkin** [comment]
Hi,
Could you try to run the following command on your RPi
```bash
> docker exec -i -t luxmedbot_database_1 /bin/sh
> psql lbs lbs
> \connect lbs;
> UPDATE DATABASECHANGELOGLOCK SET LOCKED=false, LOCKGRANTED=null, LOCKEDBY=null where ID=1;
```
then restart the application

Let me know if that helps

**Comment by vonProteus** [comment]
yes it helped 
thank you
