### ISSUE TITLE
Bot crashes after fresh install

### ISSUE THREAD

**Issue by mbiernacik** [dyrkin/luxmed-bot#21]
Hi,

I've used default docker-compose config and when I'm running bot I get following errors:
```
********************************************************
Waiting for the database server to start on port 5432
********************************************************
******** Database Server has started 
********************************************************
Starting Luxmed Booking Service  
********************************************************
,--.    ,-----.    ,---.   
|  |    |  |) /_  '   .-'  
|  |    |  .-.  \ `.  `-.  
|  '--. |  '--' / .-'    | 
`-----' `------'  `-----'  
                           
2021-06-12 19:44:23 scala.App - Starting App on eeb868db2688 with PID 8 (/app/server.jar started by root in /app)
2021-06-12 19:44:23 scala.App - No active profile set, falling back to default profiles: default
2021-06-12 19:44:27 o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data repositories in DEFAULT mode.
2021-06-12 19:44:27 o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 221ms. Found 0 repository interfaces.
2021-06-12 19:44:29 c.z.h.HikariDataSource - HikariPool-1 - Starting...
2021-06-12 19:44:29 c.z.h.HikariDataSource - HikariPool-1 - Start completed.
2021-06-12 19:44:32 l.e.jvm.JdbcExecutor - SELECT COUNT(*) FROM public.databasechangeloglock
2021-06-12 19:44:32 l.e.jvm.JdbcExecutor - SELECT COUNT(*) FROM public.databasechangeloglock
2021-06-12 19:44:32 l.e.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2021-06-12 19:44:32 l.l.StandardLockService - Successfully acquired change log lock
2021-06-12 19:44:36 l.e.jvm.JdbcExecutor - SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2021-06-12 19:44:36 l.e.jvm.JdbcExecutor - SELECT COUNT(*) FROM public.databasechangelog
2021-06-12 19:44:36 l.c.StandardChangeLogHistoryService - Reading from public.databasechangelog
2021-06-12 19:44:36 l.e.jvm.JdbcExecutor - SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2021-06-12 19:44:36 l.l.StandardLockService - Successfully released change log lock
2021-06-12 19:44:37 o.h.j.i.util.LogHelper - HHH000204: Processing PersistenceUnitInfo [
    	name: default
	...]
2021-06-12 19:44:38 org.hibernate.Version - HHH000412: Hibernate Core {5.3.7.Final}
2021-06-12 19:44:38 o.h.cfg.Environment - HHH000206: hibernate.properties not found
2021-06-12 19:44:38 o.h.a.common.Version - HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
2021-06-12 19:44:40 o.h.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL9Dialect
2021-06-12 19:44:40 o.h.e.j.e.i.LobCreatorBuilderImpl - HHH000422: Disabling contextual LOB creation as connection was null
2021-06-12 19:44:40 o.h.t.BasicTypeRegistry - HHH000270: Type registration [java.util.UUID] overrides previous : org.hibernate.type.UUIDBinaryType@16f7b4af
2021-06-12 19:44:43 o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default'
2021-06-12 19:44:45 o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'monitoringService': Unsatisfied dependency expressed through field 'bot'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bot' defined in class path resource [com/lbs/server/BootConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.lbs.bot.Bot]: Factory method 'bot' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'telegram' defined in class path resource [com/lbs/server/BootConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.lbs.bot.telegram.TelegramBot]: Factory method 'telegram' threw exception; nested exception is java.lang.IllegalArgumentException
2021-06-12 19:44:45 o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
2021-06-12 19:44:45 c.z.h.HikariDataSource - HikariPool-1 - Shutdown initiated...
2021-06-12 19:44:45 c.z.h.HikariDataSource - HikariPool-1 - Shutdown completed.
2021-06-12 19:44:45 o.s.b.a.l.ConditionEvaluationReportLoggingListener - 
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-06-12 19:44:45 o.s.b.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'monitoringService': Unsatisfied dependency expressed through field 'bot'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bot' defined in class path resource [com/lbs/server/BootConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.lbs.bot.Bot]: Factory method 'bot' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'telegram' defined in class path resource [com/lbs/server/BootConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.lbs.bot.telegram.TelegramBot]: Factory method 'telegram' threw exception; nested exception is java.lang.IllegalArgumentException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.lbs.server.Boot$.delayedEndpoint$com$lbs$server$Boot$1(Boot.scala:12)
	at com.lbs.server.Boot$delayedInit$body.apply(Boot.scala:11)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at com.lbs.server.Boot$.main(Boot.scala:11)
	at com.lbs.server.Boot.main(Boot.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bot' defined in class path resource [com/lbs/server/BootConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.lbs.bot.Bot]: Factory method 'bot' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'telegram' defined in class path resource [com/lbs/server/BootConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.lbs.bot.telegram.TelegramBot]: Factory method 'telegram' threw exception; nested exception is java.lang.IllegalArgumentException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1237)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1164)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	... 36 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.lbs.bot.Bot]: Factory method 'bot' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'telegram' defined in class path resource [com/lbs/server/BootConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.lbs.bot.telegram.TelegramBot]: Factory method 'telegram' threw exception; nested exception is java.lang.IllegalArgumentException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	... 49 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'telegram' defined in class path resource [com/lbs/server/BootConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.lbs.bot.telegram.TelegramBot]: Factory method 'telegram' threw exception; nested exception is java.lang.IllegalArgumentException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:394)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:366)
	at com.lbs.server.BootConfig$$EnhancerBySpringCGLIB$$933e01e4.telegram(<generated>)
	at com.lbs.server.BootConfig.bot(BootConfig.scala:152)
	at com.lbs.server.BootConfig$$EnhancerBySpringCGLIB$$933e01e4.CGLIB$bot$0(<generated>)
	at com.lbs.server.BootConfig$$EnhancerBySpringCGLIB$$933e01e4$$FastClassBySpringCGLIB$$7d34dd4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.lbs.server.BootConfig$$EnhancerBySpringCGLIB$$933e01e4.bot(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 50 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.lbs.bot.telegram.TelegramBot]: Factory method 'telegram' threw exception; nested exception is java.lang.IllegalArgumentException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	... 73 common frames omitted
Caused by: java.lang.IllegalArgumentException: null
	at java.util.concurrent.ForkJoinPool.checkParallelism(ForkJoinPool.java:2546)
	at java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2536)
	at scala.concurrent.impl.ExecutionContextImpl$.$anonfun$fromExecutor$1(ExecutionContextImpl.scala:127)
	at scala.concurrent.impl.ExecutionContextImpl$.fromExecutor(ExecutionContextImpl.scala:131)
	at scala.concurrent.ExecutionContext$Implicits$.global$lzycompute(ExecutionContext.scala:152)
	at scala.concurrent.ExecutionContext$Implicits$.global(ExecutionContext.scala:152)
	at scala.concurrent.ExecutionContext$.global(ExecutionContext.scala:141)
	at com.bot4s.telegram.api.GlobalExecutionContext.$init$(TelegramBot.scala:12)
	at com.lbs.bot.telegram.TelegramClient.<init>(TelegramClient.scala:13)
	at com.lbs.bot.telegram.TelegramBot.<init>(TelegramBot.scala:11)
	at com.lbs.server.BootConfig.telegram(BootConfig.scala:149)
	at com.lbs.server.BootConfig$$EnhancerBySpringCGLIB$$933e01e4.CGLIB$telegram$16(<generated>)
	at com.lbs.server.BootConfig$$EnhancerBySpringCGLIB$$933e01e4$$FastClassBySpringCGLIB$$7d34dd4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.lbs.server.BootConfig$$EnhancerBySpringCGLIB$$933e01e4.telegram(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 74 common frames omitted
```
Could you please take a look at this?

**Comment by dyrkin** [comment]
Hi,
It is hard to understand what's wrong here. Did you use the latest version? Which OS? Is this the correct URL to docker-compose you used: https://github.com/dyrkin/luxmed-bot/blob/master/docker/docker-compose.yml?

**Comment by mbiernacik** [comment]
Yep, it’s the latest version (I’ve used docker-compose file which you mentioned).
I’m running bot on turnkey linux (x86). 

Maybe you could try to run fresh instance and check if you get errors like me?

**Comment by dyrkin** [comment]
I have no this issue.
The exception is coming from the code which initiates global execution context which is actually a thread pool. There is a check which verifies parallelism level
```java
    private static int checkParallelism(int parallelism) {
        if (parallelism <= 0 || parallelism > MAX_CAP)
            throw new IllegalArgumentException();
        return parallelism;
    }
```
The actual value of the `parallelism` argument is calculated based on the number of processors available to the Java virtual machine. There is the code:
```scala
    def getInt(name: String, default: String) = (try System.getProperty(name, default) catch {
      case e: SecurityException => default
    }) match {
      case s if s.charAt(0) == 'x' => (Runtime.getRuntime.availableProcessors * s.substring(1).toDouble).ceil.toInt
      case other => other.toInt
    }

    def range(floor: Int, desired: Int, ceiling: Int) = scala.math.min(scala.math.max(floor, desired), ceiling)
    val numThreads = getInt("scala.concurrent.context.numThreads", "x1")
    // The hard limit on the number of active threads that the thread factory will produce
    val maxNoOfThreads = getInt("scala.concurrent.context.maxThreads", "x1")

    val desiredParallelism = range(
      getInt("scala.concurrent.context.minThreads", "1"),
      numThreads,
      maxNoOfThreads)

    // The thread factory must provide additional threads to support managed blocking.
    val maxExtraThreads = getInt("scala.concurrent.context.maxExtraThreads", "256")

    val uncaughtExceptionHandler: Thread.UncaughtExceptionHandler = new Thread.UncaughtExceptionHandler {
      override def uncaughtException(thread: Thread, cause: Throwable): Unit = reporter(cause)
    }

    val threadFactory = new ExecutionContextImpl.DefaultThreadFactory(daemonic = true,
                                                                      maxBlockers = maxExtraThreads,
                                                                      prefix = "scala-execution-context-global",
                                                                      uncaught = uncaughtExceptionHandler)

    new ForkJoinPool(desiredParallelism, threadFactory, uncaughtExceptionHandler, true)
```

Pay attention that it uses `Runtime.getRuntime.availableProcessors` to determine the actual number of available processors. It seems that the java virtual machine inside your docker engine which is inside your TurnKey Linux returns `0` or a negative number of available processors.
I guess this is a bug in the java virtual machine. I'll try to fix it by using the latest available image of the OpenJDK docker image.

**Comment by dyrkin** [comment]
Please pull the latest version and try to run it. If it still won't work then find the line in the log and check how many processors it prints.
`luxmedbookingservice_1  | 14:23:02.149 [main] INFO com.lbs.server.Boot$ - Num processors: 4`

**Comment by mbiernacik** [comment]
I've pulled the latest image and you were right - for some reason number of processor was 0.

I've changed how server starts from:
`cd /app && java -Xmx128m -jar server.jar`
to:
`cd /app && java -Xmx128m -XX:ActiveProcessorCount=2 -jar server.jar`
where I can overwrite ActiveProcessorCount.

Now everything works. 
Thanks
