### ISSUE TITLE
Cannot book new appointment if user has another appointment already booked

### ISSUE THREAD

**Issue by gtekiela** [dyrkin/luxmed-bot#31]
### Description
I have one appointment already booked, but I'd like to book a new one if I can visit a doctor earlier.

Monitoring service successfully detects new available visit
```
2022-02-21 18:47:45 c.l.s.s.MonitoringService - Found 1 terms by monitoring [#1]
```
and sends request to book an appointment.
```
2022-02-21 18:47:45 com.lbs.api.http.package$ - Sending request:
HttpRequest(https://portalpacjenta.luxmed.pl/PatientPortalMobileAPI/api/visits/temporary-reservation,POST,StringBodyConnectFunc({
  "ClinicId" : xxx,
  "DoctorId" : xxx,
  "PayerDetailsList" : [ {
    "BrandId" : xxx,
    "ContractId" : xxx,
    "PayerId" : xxx,
    "PayerName" : "xxx",
    "ProductElementId" : xxx,
    "ProductId" : xxx,
    "ProductInContractId" : xxx,
    "ServaAppId" : xxx,
    "ServaId" : xxx
  } ],
  "ReferralRequiredByService" : false,
  "RoomId" : xxx,
  "ServiceId" : xxx,
  "StartDateTime" : "2022-xx-xxTxx:xx:xx+01:00"
}),List(),List((User-Agent,PatientPortal/4.20.5 (pl.luxmed.pp.LUX-MED; build:853; iOS 13.5.1) Alamofire/4.9.1), (Custom-User-Agent,PatientPortal; 4.20.5; 4380E6AC-D291-4895-8B1B-F774C318BD7D; iOS; 14.5.1; iPhone8,1), 
(Connection,keep-alive), (Accept,*/*), (Accept-Language,en;q=1.0, en-PL;q=0.9, pl-PL;q=0.8, ru-PL;q=0.7, uk-PL;q=0.6), (Accept-Encoding,gzip;q=1.0, compress;q=0.5), (Host,portalpacjenta.luxmed.pl), (Content-Type,application/json), 
(Authorization,bearer xxx)),List(scalaj.http.HttpOptions$$$Lambda$1649/557142191@730c7f01, scalaj.http.HttpOptions$$$Lambda$1650/1064914070@7af126f7, scalaj.http.HttpOptions$$$Lambda$1651/1162783412@577dbf1b),None,UTF-8,4096,QueryStringUrlFunc,true,None)
```

### Bug
but it doesn't handle a case when another appointment is already booked.
```
2022-02-21 18:47:45 com.lbs.api.http.package$ - Received response:
Right(HttpResponse({"Id":xxxxxxxxx,"InformationMessages":
[{"Code":1000101030,"Title":"Close appointment dates","Message":"You have another appointment close to the one you have booked. If you are unable to attend any of the appointments, please cancel it in advance."}],
"HasReferralRequired":false,"MustTermOfReservedVisitBeChanged":false,"ReferralId":null,"Links":[{"Rel":"delete_temporary_reservation","Href":"/PatientPortalMobileAPI/api/visits/temporary-reservation/xxxxxxxxx","Method":"DELETE","ApiVersion":1}]},
201,Map(Transfer-Encoding -> Vector(chunked), Server -> Vector(Microsoft-IIS/10.0), Strict-Transport-Security -> Vector(max-age=31536000), Expires -> Vector(-1), Content-Encoding -> Vector(gzip), X-Iinfo -> Vector(18-16430118-16416945 SNYy RT(1645465664882 678) 
q(0 0 0 0) r(3 3) U6), Cache-Control -> Vector(no-cache), Content-Type -> Vector(application/json; charset=utf-8), Pragma -> Vector(no-cache), Date -> Vector(XXX, XX XXX 2022 XX:XX:XX GMT), Set-Cookie -> Vector(visid_incap_2269135=xxx; expires=XXX, XX XXX 2023 XX:XX:XX GMT; HttpOnly; path=/; Domain=.luxmed.pl; 
Secure; SameSite=None, incap_ses_686_2269135=xxx; path=/; Domain=.luxmed.pl; Secure; SameSite=None), X-AspNet-Version -> Vector(4.0.30319), X-CDN -> Vector(Imperva), X-Powered-By -> Vector(ASP.NET), Status -> Vector(HTTP/1.1 201 Created))))
2022-02-21 18:47:45 com.lbs.common.Scheduler - Unable to execute scheduler task
org.json4s.package$MappingException: No usable value for informationMessages
Do not know how to convert JObject(List((code,JInt(1000101030)), (title,JString(Close appointment dates)), 
(message,JString(You have another appointment close to the one you have booked. If you are unable to attend any of the appointments, please cancel it in advance.)))) into class java.lang.String
at org.json4s.reflect.package$.fail(package.scala:95)
at org.json4s.Extraction$ClassInstanceBuilder.buildCtorArg(Extraction.scala:547)
at org.json4s.Extraction$ClassInstanceBuilder.$anonfun$instantiate$4(Extraction.scala:567)
at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
at scala.collection.TraversableLike.map(TraversableLike.scala:237)
at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
at scala.collection.AbstractTraversable.map(Traversable.scala:108)
at org.json4s.Extraction$ClassInstanceBuilder.instantiate(Extraction.scala:567)
at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:618)
at org.json4s.Extraction$.$anonfun$extract$10(Extraction.scala:409)
at org.json4s.Extraction$.$anonfun$customOrElse$1(Extraction.scala:625)
at org.json4s.CustomSerializer$$anonfun$deserialize$2.applyOrElse(Formats.scala:409)
at org.json4s.CustomSerializer$$anonfun$deserialize$2.applyOrElse(Formats.scala:409)
at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
at org.json4s.Extraction$.customOrElse(Extraction.scala:625)
at org.json4s.Extraction$.extract(Extraction.scala:401)
at org.json4s.Extraction$.extract(Extraction.scala:40)
at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
at com.lbs.api.json.JsonSerializer$.extract(JsonSerializer.scala:24)
at com.lbs.api.json.JsonSerializer$extensions$JsonStringToObject.as(JsonSerializer.scala:35)
at com.lbs.api.LuxmedApi.$anonfun$post$1(LuxmedApi.scala:177)
at scala.util.Either.map(Either.scala:353)
at cats.instances.EitherInstances$$anon$2.map(either.scala:58)
at cats.instances.EitherInstances$$anon$2.map(either.scala:41)
at cats.Functor$Ops.map(Functor.scala:233)
at cats.Functor$Ops.map$(Functor.scala:233)
at cats.Functor$ToFunctorOps$$anon$4.map(Functor.scala:250)
at com.lbs.api.LuxmedApi.post(LuxmedApi.scala:177)
at com.lbs.api.LuxmedApi.temporaryReservation(LuxmedApi.scala:101)
at com.lbs.server.service.ApiService.$anonfun$temporaryReservation$1(ApiService.scala:78)
at com.lbs.server.service.SessionSupport.$anonfun$withSession$3(SessionSupport.scala:53)
at scala.util.Either.flatMap(Either.scala:341)
at com.lbs.server.service.SessionSupport.doApiCall$1(SessionSupport.scala:52)
at com.lbs.server.service.SessionSupport.withSession(SessionSupport.scala:58)
at com.lbs.server.service.SessionSupport.withSession$(SessionSupport.scala:24)
at com.lbs.server.service.ApiService.withSession(ApiService.scala:17)
at com.lbs.server.service.ApiService.temporaryReservation(ApiService.scala:76)
at com.lbs.server.service.ApiService.reserveVisit(ApiService.scala:97)
at com.lbs.server.service.MonitoringService.bookAppointment(MonitoringService.scala:148)
at com.lbs.server.service.MonitoringService.monitor(MonitoringService.scala:77)
at com.lbs.server.service.MonitoringService.$anonfun$initializeMonitorings$2(MonitoringService.scala:105)
at com.lbs.common.Scheduler.$anonfun$silentFn$1(Scheduler.scala:23)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
Caused by: org.json4s.package$MappingException: Do not know how to convert JObject(List((code,JInt(1000101030)), (title,JString(Close appointment dates)), 
(message,JString(You have another appointment close to the one you have booked. If you are unable to attend any of the appointments, please cancel it in advance.)))) into class java.lang.String
at org.json4s.reflect.package$.fail(package.scala:95)
at org.json4s.Extraction$.convert(Extraction.scala:728)
at org.json4s.Extraction$.$anonfun$extract$10(Extraction.scala:403)
at org.json4s.Extraction$.$anonfun$customOrElse$1(Extraction.scala:625)
at org.json4s.CustomSerializer$$anonfun$deserialize$2.applyOrElse(Formats.scala:409)
at org.json4s.CustomSerializer$$anonfun$deserialize$2.applyOrElse(Formats.scala:409)
at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
at org.json4s.Extraction$.customOrElse(Extraction.scala:625)
at org.json4s.Extraction$.extract(Extraction.scala:401)
at org.json4s.Extraction$.org$json4s$Extraction$$extractDetectingNonTerminal(Extraction.scala:424)
at org.json4s.Extraction$CollectionBuilder.$anonfun$mkCollection$1(Extraction.scala:431)
at scala.collection.immutable.List.map(List.scala:286)
at org.json4s.Extraction$CollectionBuilder.mkCollection(Extraction.scala:431)
at org.json4s.Extraction$CollectionBuilder.result(Extraction.scala:451)
at org.json4s.Extraction$.$anonfun$extract$9(Extraction.scala:391)
at org.json4s.Extraction$.$anonfun$customOrElse$1(Extraction.scala:625)
at org.json4s.CustomSerializer$$anonfun$deserialize$2.applyOrElse(Formats.scala:409)
at org.json4s.CustomSerializer$$anonfun$deserialize$2.applyOrElse(Formats.scala:409)
at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
at org.json4s.Extraction$.customOrElse(Extraction.scala:625)
at org.json4s.Extraction$.extract(Extraction.scala:391)
at org.json4s.Extraction$ClassInstanceBuilder.buildCtorArg(Extraction.scala:535)
... 50 common frames omitted
```

### Expected behavior:
Service should cancel previous booking and book a new one

**Comment by dyrkin** [comment]
Hi,

Did you answer Yes on “ ➡ Do you want to update term if reservation already exists?” question?

**Comment by dyrkin** [comment]
Did it book twice the same service or only the first left and the second is failed?

**Comment by dyrkin** [comment]
this one was probably fixed as we moved to the new luxmed API. please check and reopen the issue if it still behaves like this
