### ISSUE TITLE
unable to search or book an appointment because of org.jasypt.exceptions.EncryptionOperationNotPossibleException

### ISSUE THREAD

**Issue by amateja** [dyrkin/luxmed-bot#71]
Hi,

When I type in some answers like city name or location I get following exception. I can reach the step with the summary and find terms button using previous searches but as soon as I hit findTerms button there is the same result.

I'm running the latest docker image.

```
2024-05-21 13:44:13 c.l.s.conversation.Book - Step execution failed
org.jasypt.exceptions.EncryptionOperationNotPossibleException: null
	at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.decrypt(StandardPBEByteEncryptor.java:1169)
	at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.decrypt(StandardPBEStringEncryptor.java:738)
	at org.jasypt.util.text.StrongTextEncryptor.decrypt(StrongTextEncryptor.java:118)
	at com.lbs.server.service.ApiService.fullLogin(ApiService.scala:151)
	at com.lbs.server.service.SessionSupport.auth$1(SessionSupport.scala:28)
	at com.lbs.server.service.SessionSupport.getSession$1(SessionSupport.scala:38)
	at com.lbs.server.service.SessionSupport.doApiCall$1(SessionSupport.scala:48)
	at com.lbs.server.service.SessionSupport.withSession(SessionSupport.scala:54)
	at com.lbs.server.service.SessionSupport.withSession$(SessionSupport.scala:22)
	at com.lbs.server.service.ApiService.withSession(ApiService.scala:18)
	at com.lbs.server.service.ApiService.getAvailableTerms(ApiService.scala:64)
	at com.lbs.server.conversation.Book.$anonfun$requestTerm$1(Book.scala:167)
	at com.lbs.server.conversation.Book.$anonfun$requestTerm$1$adapted(Book.scala:166)
	at com.lbs.server.conversation.base.Conversation.executeCurrentStep(Conversation.scala:27)
	at com.lbs.server.conversation.base.Conversation.executeCurrentStep$(Conversation.scala:24)
	at com.lbs.server.conversation.Book.executeCurrentStep(Book.scala:22)
	at com.lbs.server.conversation.base.Interactional$$anon$1$$anonfun$receive$1.applyOrElse(Interactional.scala:33)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at com.lbs.server.conversation.base.Interactional$$anon$1.aroundReceive(Interactional.scala:28)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by dyrkin** [comment]
Hi. Have you changed SECURITY_SECRET recently? If so try to `/login` again

**Comment by amateja** [comment]
Hi. Yes, I've got an idea to change the `SECURITY_SECRET` but I did not login again. Following your recommendation I did successfully just now but still it doesn't look good as I'm receiving:
`2024-05-22 09:52:25 c.l.b.t.TelegramClient - Sending telegram request: SendMessage(Chat(2067852476),Luxmed API exception: Session expired,Some(HTML),None,None,None,None,None,None,None)`

I also tried to remove the account but this has not been implemented yet.
`2024-05-22 10:06:41 c.l.b.t.TelegramClient - Sending telegram request: SendMessage(Chat(2067852476),Not implemented yet,Some(HTML),None,None,None,None,None,None,None)`

Adding the same account again also has the same effect as logging in again.

Do you have some other ideas?

**Comment by dyrkin** [comment]
Hi. Now update bot to the latest version. The Session expired error has been fixed recently

**Comment by amateja** [comment]
Much appreciated @dyrkin. Now it works like a charm.

To sum up for other users - for my initial issue changing `SECURITY_SECRET` and logging again helped and for the session expired error updating to the latest docker image. Reporting the issue I was on 1.1.49 which was the latest at that time but shortly after current version has been published.

Many thanks @dyrkin for you support and this nice software.
